INSERT INTO STAFF (SNO,SNAME,SROLE)
VALUES (1337,'CONOR','DRIVER');
INSERT INTO STAFF (SNO,SNAME,SROLE)
VALUES (1234,'JOHN','DRIVER');
INSERT INTO STAFF (SNO,SNAME,SROLE)
VALUES (1876,'LAURA','INSPECTOR');


INSERT INTO CLAIMDESC (CDNO,CDDATE,CDLOCATION,CDDESCRIPTION)
VALUES (1,01/JANUARY/2020,'CELBRIDGE','HIT BY BUS MIRROR');
INSERT INTO CLAIMDESC (CDNO,CDDATE,CDLOCATION,CDDESCRIPTION)
VALUES (2,01/FEBRUARY/2020,'MAYNOOTH','COLLISION WITH BUS');
INSERT INTO CLAIMDESC (CDNO,CDDATE,CDLOCATION,CDDESCRIPTION)
VALUES (3,01/FEBRUARY/2020,'NAAS','PASSENGER FELL ON STAIRS');

INSERT INTO CLAIM_TO_STAFF (CLAIMDESC_CDNO,STAFF_SNO)
VALUES (1,1337);
INSERT INTO INTO CLAIM_TO_STAFF (CLAIMDESC_CDNO,STAFF_SNO)
VALUES (2,1234);
INSERT INTO INTO CLAIM_TO_STAFF (CLAIMDESC_CDNO,STAFF_SNO)
VALUES (3,8765);

INSERT INTO CLAIMANT (CNO,CNAME,CADDRESS)
VALUES (100,'MARY','CELBRIDGE');
INSERT INTO thirdparty  (tpno,tpname,tpemail)
VALUES (101,'LEIA','STRAFFAN');
INSERT INTO thirdparty  (tpno,tpname,tpemail)
VALUES (102,'ALEX','KILDARE');

INSERT INTO CLAIM (CLNO,CLSTATUS,CLDESC,CONFIRMATION,EXPERTS_EXNO,CLAIMDESC_CDNO)
VALUES (200,'S','PERSONAL INJURY','c',901,1);
INSERT INTO CLAIM (CLNO,CLSTATUS,CLDESC,CONFIRMATION,EXPERTS_EXNO,CLAIMDESC_CDNO)
VALUES (201,'X','DIDNT ACTUALLY HAPPEN - NO PROOF','R',902,2);
INSERT INTO CLAIM (CLNO,CLSTATUS,CLDESC,CONFIRMATION,EXPERTS_EXNO,CLAIMDESC_CDNO)
VALUES (202,'S','BUS TOOK SUDDEN TURN','c',903,3);

INSERT INTO CLAIM_TO_EXPERT (EXPERTS_EXNO,CLAIM_CLNO,EXPERTSREPORT_EXRNO)
VALUES (901,200,25);
INSERT INTO CLAIM_TO_EXPERT (EXPERTS_EXNO,CLAIM_CLNO,EXPERTSREPORT_EXRNO)
VALUES (902,201,66);
INSERT INTO CLAIM_TO_EXPERT (EXPERTS_EXNO,CLAIM_CLNO,EXPERTSREPORT_EXRNO)
VALUES (903,202,11);

INSERT INTO PAYMENTS (PNO,CHEQUENO,PAMOUNT,PDATE,PAYEE)
VALUES (81,4001, 5000, 01/JUNE/2020, 'MARY');
INSERT INTO PAYMENTS (PNO,CHEQUENO,PAMOUNT,PDATE,PAYEE)
VALUES (82,4002,0, 01/FEBRUARY/2020), 'LEIA');
INSERT INTO PAYMENTS (PNO,CHEQUENO,PAMOUNT,PDATE,PAYEE)
VALUES (83,4003, 10000, 01/AUGUST/2020, 'ALEX');

INSERT INTO PAYMENT_TO_CLAIM (PAYMENTS_PNO,CLAIM_CLNO)
VALUES (61,200);
INSERT INTO PAYMENT_TO_CLAIM (PAYMENTS_PNO,CLAIM_CLNO)
VALUES (62,201);
INSERT INTO PAYMENT_TO_CLAIM (PAYMENTS_PNO,CLAIM_CLNO)
VALUES (63,202);

INSERT INTO EXPERTS (EXNO,EXNAME,EXADDRESS,EXAREA,CLAIM_CLNO)
VALUES (901,'DARRAGH','DUBLIN','INSURANCE',200);
INSERT INTO  EXPERTS (EXNO,EXNAME,EXADDRESS,EXAREA,CLAIM_CLNO)
VALUES (902,'REBECCA','WICKLOW','RISK ASSESSMENT',201);
INSERT INTO  EXPERTS (EXNO,EXNAME,EXADDRESS,EXAREA,CLAIM_CLNO)
VALUES (903,'jess','cork','MEDICAL',202);

INSERT INTO witnesstoclaim (witness_witnessid,claim_claimno,claim_wrno)
VALUES (33,99,25);
INSERT INTO witnesstoclaim (witness_witnessid,claim_claimno,claim_wrno)
VALUES (32,85,66);
INSERT INTO witnesstoclaim (witness_witnessid,claim_claimno,claim_wrno)
VALUES (35,76,11);

INSERT INTO witnessreport (wrno,wrdate,wrdescription,witness_witnessid,claim_claimno,claim_wrno)
VALUES (25,TO_DATE('01-01-1998','MM-DD-YYYY'),'happened',33,99,25);
INSERT INTO witnessreport (wrno,wrdate,wrdescription,witness_witnessid,claim_claimno,claim_wrno)
VALUES (66,TO_DATE('01-10-2012','MM-DD-YYYY'),'did not happened',32,85,66);
INSERT INTO witnessreport (wrno,wrdate,wrdescription,witness_witnessid,claim_claimno,claim_wrno)
VALUES (11,TO_DATE('11-04-2021','MM-DD-YYYY'),'happened',35,76,11);